### ISSUE TITLE
Finish schema

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/theherdbook#1]
Finish the database schema.

**Comment by kusalananda** [comment]
The current schema is work in progress and located on the `develop` branch in the `sql` subdirectory: https://github.com/NBISweden/theherdbook/tree/develop/sql

**Comment by kusalananda** [comment]
With commit 10b3786, the schema may be loaded successfully into a PostgreSQL database.

**Comment by pontus** [comment]
From discussions/user stories, it seems we will have at least three distinct roles/relations.

* Some sort of global administrator- can do everything
* Genebank administrators that can perform a given set of operations on their associated gene bank(s) (and corresponding animals?)
* Genebank owners that can perform a given set of operations on particular animals in a gene bank.

I think we'll want the genebank admin/owners relations as many to many for user, individuals (other suggestions)?

For users; I've definitely seen it to be a good idea to have a conceptual user to which one can link federated identities (typically), so something like (untested)

```
CREATE TABLE user (
  user_id   SERIAL PRIMARY KEY,
  email      VARCHAR(200) NOT NULL,
 privileges  VARCHAR(200) 
);
```

and 

```
CREATE TYPE auth_type AS ENUM ('federated', 'password', 'totp');
-- publickey and so on?

CREATE TABLE authenticators (
   auth_id SERIAL PRIMARY KEY,
   user_id  INTEGER NOT NULL,
   auth auth_type NOT NULL,
   auth_data VARCHAR(65535),
   FOREIGN KEY (user_id) references user(user_id)
);
```

?

**Comment by kusalananda** [comment]
It sounds like the `user` should have a `role`, which may be an `ENUM`. The roles could be `user`, `admin`, `genebank_admin`, and `genebank_owner`. I presume this would be instead of the `privileges` field that you suggest.

In the `authenticators` table, I'm assuming `auth_data` should be a hashed representation of something? Maybe tyrn this into a `TEXT` field rather than a long `VARCHAR`, or `BYTEA` if it ever can be binary?

**Comment by pontus** [comment]
For role, that depends on how it's defined; neither of these is a "static" privilege that give permissions to perform operations on any object - they are tied to specific genebanks/animals AFAIU.

These could, of course, be encoded into `privileges`, but I'd rather not. I mostly see it as somewhere to handle the "global admin" role and some future-proofing.

**Comment by pontus** [comment]
For `auth_data`, TEXT is likely fine (and definitely if we only care about postgres). It's been a few years and I haven't kept up, but IIRC that used to be the most portable way of getting a largish text supporting type.

I envision what goes into `auth_data` will be specific to the `auth_type` (e.g. for ` federated`, it might be expected values for `iss` and `sub` in a claim, or a provider id and a username), but we can decide for it to be non-binary at least.

**Comment by andkaha** [comment]
This is now either done or outdate, as far as I am concerned.

Closing
