### ISSUE TITLE
External Dummy Herds

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#118]
Now animals that are sold outside a registred herd is still active in the founder herd. One way of solving this is by the comment below

**Comment by jhagberg** [comment]
This could just be handled in Import all rabbits with "NyGenbank" = 0 ends up in the dummy heard "GX001" or similar.
Also, it should be some easy functions when selling a rabbit to an external herd or just clear instructions.

**Comment by andkaha** [comment]
@jhagberg 
Is this just for Mellerud, not for Gotlandskanin? Should the dummy herd maybe be called `MX001` (initial `M` for "Mellerud").  Is it enough with a single dummy herd, or should multiple ones be created according to some criteria?

**Comment by jhagberg** [comment]
Its for both and I will update the issue.
