### ISSUE TITLE
Current data issues: duplicated certificate numbers

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/theherdbook#12]
The following certificate numbers ("intyg") are duplicated in the data set:

```
5222
6165
9587
13478
13480
16657
17296
50914
51168
```

Each of these occur exactly twice.

**Comment by kusalananda** [comment]
This issue requires a "weakened" database schema where the `certificate` no longer is unique. I would like this issue to be resolved with priority. See commit 1caa180.

**Comment by andkaha** [comment]
Included in data issue summary document.

**Comment by andkaha** [comment]
Update:  The most recent data set that I have have the following three certificates duplicated (twice):

```
16657
17296
6165
```

**Comment by kusalananda** [comment]
It's still an issue that some certificates are duplicated. I can currently see tho following duplications:
```
 count | certificate
-------+-------------
     2 | 11210
     2 | 11664
     2 | 17296
     2 | 10746
     2 | 8561
     2 | 11425
     2 | 7356
     2 | 12617
     2 | 1263
     2 | 16657
     2 | 2987
     2 | 13112
     2 | 10994
     2 | 4944
     7 | ?
     2 | 12988
     2 | 6165
     2 | 1583
     2 | 10854
(19 rows)
```

Additionally, there are 399 individuals whose certificate is missing.

**Comment by andkaha** [comment]
This is still an issue in Gotlandskanin:
```
 count | certificate
-------+-------------
     2 | 17296
     2 | 16657
     7 | ?
     2 | 6165
(4 rows)
```
and in Mellerudskanin:
```
 count | certificate
-------+-------------
     2 | 11664
     2 | 7356
     2 | 12988
     2 | 10994
     2 | 10746
     2 | 8561
     2 | 12617
     2 | 10854
(8 rows)
```

Additionally, 399 individuals don't have a certificate at all.
