### ISSUE TITLE
Current data issues: strangely formatted certificate numbers

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/theherdbook#13]
The certificates with numbers `f` (just the letter `f`, no actual number) is a strange one. Likewise, there is one `m10217` and seven `?`. There are 97 that are zero (the character `0`) and 250 that are empty (null string).

I'm assuming that the ones that are zero, empty, or `?`, are unknown.

**Comment by andkaha** [comment]
Included in data issue summary document.

**Comment by andkaha** [comment]
We'll implement some form of health check in the web interface later.
