### ISSUE TITLE
Edit animals

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#133]
as a Genebank manager, I would like to edit all fields of an animal. 

as a herd owner, I want to edit all fields of an animal as long as it's not submitted to the genebank manager to be "registered"
as a herd owner, I want to edit the field of a registered animal that is not locked. 
As a herd owner, you should only be able to edit animals where you own the origin herd, not animals bought and added to your herd.

The only fields that are locked are "certificate number", and "individual number"

**Comment by jhagberg** [comment]
closed by #157

**Comment by jhagberg** [comment]
linked to #161

**Comment by pontus** [comment]
Most things should probably be editable by herd owners.

**Comment by pontus** [comment]
Possibly give warning about certificate if editing fields within it?

**Comment by jhagberg** [comment]
A herd owner should be able to edit all animals they currently own..

**Comment by HenrikeW** [comment]
As far as I can see this should be the case now. I found a bug though that I described in #431. 
So I think we could close this issue.

**Comment by jhagberg** [comment]
And #401  should be fixed also

**Comment by jhagberg** [comment]
Backend needs to support changing number.

**Comment by jhagberg** [comment]
Should be fixed now
