### ISSUE TITLE
Approve new rabbit added by a herd owner

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#134]
This should be an action taken by the genebank manager, following a request from the owner of an animal to have it included in the genebank.

One way of implementing this is to add database fields for genebank request (timestamp + user) and acceptance/rejection (timestamp + manager), (along with frontend interfaces and api endpoints).

**Comment by pontus** [comment]
This should probably no longer be the case, rather herd owners should be able to add rabbits for which they have paper certificates without approval.

**Comment by jhagberg** [comment]
Yes requriments have changed
