### ISSUE TITLE
Work Environment

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#14]
- [x] Servers for development
- [x] Relevant working environments
- [x] SSC account

**Comment by pontus** [comment]
I think we had a quick discussion about this and there did not seem to be any issues, but just to check; do we know anything about constraints for the provided solution here? Just thinking that our partner is a non-profit and without knowing if they have funding in the future, it's difficult to know whatever costs of e.g. $30/month would be problematic or if this is not a concern.

I've applied for a SSC project (SNIC 2020/20-15) for development work.

**Comment by jhagberg** [comment]
Perhaps SSC can host the site later on also? Now they have one.com and we can probably not host this there. Bu I am open for suggestions!
