### ISSUE TITLE
Change Url in browser when clicking "min  besättning"

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#164]
When clicking "min Besättning" the URL displayed in the browser is "Owner" 
I think it is better if this URL is the right own /herd/G1237 or similar so one can copy-paste the URL to my own herd and share that

"herd" part should also be Swedish I think or if it works to skip that part if possible 
or use short
 /h/G1237 for herd or /b/ för besättning
 /i/G1237-1237 or /i/ individ or /k/ för kanin.

**Comment by jhagberg** [comment]
This wont work if you have both Mellerud and Gottis Herd Right...

**Comment by norling** [comment]
yes - the current system was designed to allow you to have multiple herds... we could try setting the url like `/owner/G1237` maybe? and have the url redirect to `herd/G1237` if you're not the owner?
