### ISSUE TITLE
Login page is showing when reloading or open in new window runnin dev environment

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#178]
In Linux
Version 86.0.4240.183 (Official Build) (64-bit)

run from develop branch 

```
wget https://raw.githubusercontent.com/NBISweden/theherdbook/6ae68977bb423b0c12ae4abc40a2c3bbfc4cc977/dc-current-branch.yml
GITHUB_REF="$(git rev-parse --abbrev-ref HEAD)"
export TAG=${GITHUB_REF##*/}
docker-compose -f dc-current-branch.yml pull
docker-compose -f dc-current-branch.yml up
```
go to localhost:8080

login with your user and go to a genbank view press reload or klick on a herd and then "öppna" i eget fönster 

then the user is redirected to /login and for a short moment, the login box is showed.

**Comment by HenrikeW** [comment]
I started to investigate this but couldn't solve it yet. This is what I found so far:
- when reloading a URL like this one `http://localhost:8080/herd/G308` the `Restricted`-function defined in `navigation.tsx` line 37 is called seven times. 
- the first three times, the `user`-object is `null` which makes `Restricted` redirect to the login-page and the buggy behavior described above occurs.
- after three calls, the console logs a user object, originating from an asynchronous function `handleLogin` in `user_context.tsx`line 72 that also updates the `user`-state in `WithUserContext`. 
- after this, `user` in the `Restricted`-function contains the same user object and `Restricted` now renders whatever is inside `props.children`, in this case `HerdView`. 

I'm still not sure, where the `handleLogin`-function is called, and why. Why does the `user`-state need to be updated if the user is still the same? 
My guess is, if the `user`-state never returned to `null`, we wouldn't see the redirect to the login page. 

In a descriptive comment in `user_context.tsx` someone has written this:
_" The actual user state is stored in a cookie synced with a session on the backend.
  When this component is mounted it checks if there is currently a cookie and sets
  the state accordingly if so."_

It sounds like it could be related, but it doesn't give me any clue, unfortunately. 
Anyone of you has an idea how to solve this?
