### ISSUE TITLE
Use flask built in jsonifier for returns?

### ISSUE THREAD

**Issue by pontus** [NBISweden/theherdbook#196]
Should we let flask handle jsonifying by returning a dict rather than converting to a string containing json? Should anything return anything other than json.

**Comment by jhagberg** [comment]
Yes we are thinking of using the Python API instead of directly talk to the sql server in the R-api but then we need a more efficient protocol than json. Plain csv or feather or similar.

**Comment by pontus** [comment]
Performancewise I suspect anything works, it mostly depends on how things can be handled on the R side (but it would be very good if one could get rid of the direct database connection there).

**Comment by jhagberg** [comment]
R sucks at json. Yes much better if we can control what R gets from the python API so we do not need to update the sql every db change!
