### ISSUE TITLE
Add initial test mating functionality

### ISSUE THREAD

**Issue by inghylt** [NBISweden/theherdbook#201]
Create front end functionality that allows users to:
- Select a father from list of all active males from chosen genebank
- Select a mother from list of all active females from chosen genebank

Allow filtering for number, name and year (case insensitive)

Since the R-api is not currently in shape, the first iteration will only present chosen father and mother. Next iteration will actually calculate and present the inbreeding coefficient

**Comment by jhagberg** [comment]
This is fixed
