### ISSUE TITLE
inefficient herd fetching

### ISSUE THREAD

**Issue by norling** [NBISweden/theherdbook#205]
Requesting herd information can be very slow for large herds, this is mostly visible with the GX1 herd.

**Comment by pontus** [comment]
Investigate, if easy, do fix. If not, we can live with this.

**Comment by pontus** [comment]
Seems like also small herds can be slow to load.

**Comment by jonandernovella** [comment]
Bug found. It's on the frontend side and related to misuse of the react useMemo hook.

https://github.com/NBISweden/theherdbook/blob/5efb91d407e320435960b46b79df18da7e6c3c00/frontend/src/herd_view.tsx#L71
