### ISSUE TITLE
Breeding form incorrect use of map

### ISSUE THREAD

**Issue by danr** [NBISweden/theherdbook#210]
Found this:
https://github.com/NBISweden/theherdbook/blob/e5452b5e565c8cb185d4d5574efc369cb5162def/frontend/src/breeding_form.tsx#L64-L70
If `genebanks` has more than one element you will only get results from the first genebank because you're using `genebanks.map(...)[0]`. :christmas_tree:

**Comment by norling** [comment]
This is intended, as anything other than one result would be an error, but maybe I should do something else about that... I never really know what to do with frontend errors. Things like this isn't interesting to the user, writing them to the console doesn't really help anyone, and writing some service to send them to the backend for logging seems like it'd get noisy _really_ fast...
