### ISSUE TITLE
Import script is not creating breeding IDs for founders

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#222]
Founder animals without mother and father does not have a breeding value/event and thus no breeding ID in the indvidual table

**Comment by andkaha** [comment]
Is this not ok and expected? What requires a founder animal to have a breeding event?

**Comment by jhagberg** [comment]
Think this is fixed in pr #223 

The way we list animals now for the R-API the founders are missing and thus the R-API complains about missing parents. Ideally, we want to send all existing animals to the R-API to be able to calculate the inbreeding from the offsprings. We also want to list the Founder animals in the Web interface and now if they do not have a breeding event they are not listed
