### ISSUE TITLE
Rabbit exists in two herds

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#224]
There is a Data load bug if a rabbit is sold to an external herd the same year as it is born.
Then it will exist in two herds. 
I simple workaround is to change the line in the external herd tracking function. But could probably be solved in a better way

```
-               MAKE_DATE(DATE_PART('year', ht.herd_tracking_date)::integer, 12, 31)
+               MAKE_DATE(DATE_PART('year', ht.herd_tracking_date)::integer+1, 12, 31)

```

**Comment by andkaha** [comment]
Do you have an example animal for which this happens?

**Comment by jhagberg** [comment]
Yes I sent you this on slack

**Comment by andkaha** [comment]
It is not really that they were sold externally the same year that they were born, but that more than one transfer was made in the space of a single year.  Using the animal `G1004-1417` as an example, it was born on 2014-04-15 into herd_id 7. In 2016 it was transferred to herd_id 84, and later that same year sold externally.

The workaround is to use the `herd_tracking` data with the highest `herd_tracking_id` number, as that would have been added later.
