### ISSUE TITLE
As a Genebank manager I want to be able to manually add an animal to the Genebank for any local herds

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#23]
As a genebank manager, a herd owner may send me certificates that are not in the system yet.
I would like to add the information on that certificate to this system. I want the permission to do this to any herd in the genebank I manage, and a form to add the information.

An example of such a certificate can be found in the Drive project folder:https://drive.google.com/file/d/1R5inu0sC273exAYRQeCQCpJBWE-ZqtPn/view?usp=sharing

First it should be only for manager since herd can add animals using the "record birth"

- The same form as the certificate generation can be used, with the option to upload a digital copy of the certifikate. 
- No digital certificate is needed for the reported animal (these animals already have a paper certificate), but the manager needs to manually input all the data into the system. 
- It should not be possible to add an animal where a parents do not exist in the system already.

**Comment by jhagberg** [comment]
First it should be only for manager since herd can add animals using the "record birth"

It could use the same form as the certificate generation with the option to upload a digital copy of the certifikate. I  do not think a manger wants to create a digital certificate of a reporterd animal. They should only get mail about a rabbit that already have a paper certificate. So he manually need to input all the data. It should not be possible to ad an animal where a parent does not exist in the system already.

**Comment by HenrikeW** [comment]
After the first draft, some things need to be fixed:

- [x] for the genebank managers, the form to add a rabbit shouldn't be located in connection to a herd, but rather independently, with an additional field to specify to which herd the rabbit should be added (closer to today's workflow and more convenient)
- [x] when one rabbit has been added, it should be easy to add the next one. Two buttons: 1. "Lägg till kanin" that just clears the form. 2. "Lägg till kull-syskon" that clears the form but keeps mother, father, birth date and origin herd (i.e. first part of the number).
- [x] when a rabbit is added, its herd tracking values should be updated (backend)
