### ISSUE TITLE
Founders is not listed in the Genebank list

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#231]
Founders now have breeding ID but the breeding.father_id and mother_id is Null 

since the Individual.select in data_access.py is doing a lef join on Father.id == to Breeding.father_id the founders with Null is not selected I think.

**Comment by andkaha** [comment]
I _think_ PR #232 fixes this, but please test.

**Comment by pontus** [comment]
I just tested setting the `birth_date` in the breeding for a founder, but it still doesn't show up in the API individual list for me (and this makes sense, but I thought I'd verify it).

**Comment by andkaha** [comment]
This seems to have been fixed by #232 after all.

**Comment by pontus** [comment]
A litle post mortem; it seems this was caused by the lack of any herd tracking entry for the individual.
