### ISSUE TITLE
Correct "yearly columns" for returning animals

### ISSUE THREAD

**Issue by andkaha** [NBISweden/theherdbook#237]
Find and correct the "yearly columns" of animals that were sold outside of the system and later returned.

**Comment by andkaha** [comment]
Examples of affected animals: G1004-1417, G1004-1512, G1004-1712, G1004-1713, G1016-1551, G1023-1421

**Comment by andkaha** [comment]
I can't see how these could be found programmatically.

**Comment by jhagberg** [comment]
Search for all animals with "0" in NyG. Then search for each yearly column >= birth year. If any yearly column starting from birth year is empty and then later have a herdnumber. We should replace the empty years with 0 in the yearly report column. Or just fix the history. 

But first let's find all rabbits matching this and I can manually check some of them.

**Comment by andkaha** [comment]
The Gotlandkanin animals affected (118 animals).  Note that some of the ones that you mentioned, @jhagberg, are not included since their birth year column was non-empty.
```
5-0651          354-0614        588-1023        689-1713        1074-1644
106-0731        354-0615        618-0721        689-1714        1104-1511
106-0756        357-0321        632-0932        689-1725        1115-1727
106-0822        357-0512        632-1121        694-1584        1155-1624
106-0844        388-124a        645-0912        716-1627        1158-1723
107-0912        406-0713        646-1015        716-1712        1163-1781
140-041         406-0724        646-1212        718-1424        1163-1792
167-015         414-0613        649-0822        745-1011        1185-1815
167-0752        425-0532        649-0826        752-1013        1211-1713
167-1244        434-0722        649-0827        774-1115        1216-1611
167-1261        479-0415        660-13141       783-1314        1245-1734
167-1273        493-0723        660-1523        855-1422        1259-1816
167-132         493-0735        674-0914        870-1212        1273-1713
167-1375        493-0762        677-0922        871-1611        1273-1733
172-0726        494-0644        677-1615        871-1612        1310-1834
172-1031        503-0414        678-1022        888-1314        1316-1822
172-1036        518-1222        678-1121        888-1316        1319-1811
183-122         525-0813        682-1011        970-1307        1322-1713
269-015         525-0852        686-1642        1004-1417       1330-1861
276-1119        529-0981        686-1645        1004-1712       1391-1912
282-112         550-0642        686-1712        1023-1421       1406-1942
304-0621        550-0664        686-1713        1044-1411
304-0923        567-0932        686-1725        1051-1423
304-1239        588-0723        689-1322        1074-1633
```

```
csvgrep -c 14 -r '^0$' G20210227.csv |
csvcut -c 4,6,21-41 |
awk -F , '
    NR > 1 {
        col = 2020 - $2 + 3
        empty = 0
        for (i = col; i > 2; --i)
            if ($i == "") empty = 1; else if (empty) { print $1; next }
    }' |
sort -n | column
```

**Comment by andkaha** [comment]
Anders replies:

>Som Andreas är inne på vad gäller 0 i kolumnen ny genbank, så ska det faktiskt vara så, åtminstone har det varit min avsikt, att en nolla där betyder att den från uppfödande genbank sålts till någon som saknar genbank. Har någon vidaresålt en kanin till någon som saknar genbank har jag inte skrivit något i kolumnen "ny genbank", utan då i stället skrivit en kommentar i kolumnen "Övrigt" att kaninen sålts vidare till någon som inte har genbank.
>
>Fenomenet att en nollad kanin plötsligt dyker upp i en genbank i årtalskolumn beror allra oftast på att den sålts till någon som saknar genbank, men att denne någon sedan ansökt och fått genbanksstatus. Kaninen har alltså inte bytt ägare, utan ägaren har senare fått genbanksstatus. Det är mer regel än undantag att det går till på det viset - först köper man några kaniner, sedan går man med i föreningen och ansöker om genbank med de kaniner man köpt som startdjur. Det är ju så för att kunna få godkänd genbank, att man måste ange med vilka kaniner man avser att starta genbanken med.
>
>Hoppas detta gör att det klarnar, åtminstone lite.
