### ISSUE TITLE
Import Gotlandskanin create a rabbit with null parents

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#260]
G1475-2011
This rabbit is missing a father but is  when listing the rabbit imported he is listed as a founder with both father and mother as null
He should be added as a regular individual since he has his father and mother specified in the xls file

When I look further it seems to affect all animals with one missing parent
all G1475-20**  

So they should not be imported as father-mother null 
I guess the correct way is to exclude them from the import altogether instead of adding them as false founders.

**Comment by jhagberg** [comment]
Is this solved?

**Comment by andkaha** [comment]
The individuals are added to the database even if they are missing a parent. They are not excluded. The breeding event for that individual would list the parent that is not missing (this may have been fixed since May?). There is nothing in the database that tags an animal as a founder.

**Comment by andkaha** [comment]
Sorry, I noticed now that both parents are indeed NULL in the breeding event.  I will look into this.

**Comment by andkaha** [comment]
Should now be handled by PR #422.

The affected animals will now be associated with breeding events that has at least a mother.

**Comment by jhagberg** [comment]
I think you did a health check for this ?

**Comment by andkaha** [comment]
> I think you did a health check for this ?

Yes, this is what is reported as `Missing mothers` and `Missing fathers` while loading the data.

The most recent data sets that you gave me don't seem to have issues.

The older data set that I was working with had a few missing parents.

**Comment by andkaha** [comment]
I've double checked now and no, the most current data set does not have an issue with missing parents.

Any such parents would have been reported by the already present health checks that are run at loading time.

If this fixes this issue, consider closing this along with the un-merged PR #422.
