### ISSUE TITLE
As a herd owner I want to be able to seek registration so I can request access to my gene bank

### ISSUE THREAD

**Issue by pontus** [NBISweden/theherdbook#27]
I am a herd owner and member of the organization Gotlandskaninen. I would like to start using this very nice system. I would like to apply for an account and to be the Herd owner of my herd. 

I am a genebank manager I would like the herd owners to specify what herd number they have when they register so I can approve the registration after I check our internal membership list. If everything is good I just need to approve the application.

**Comment by jhagberg** [comment]
I figure it should be a user registration form

- Email
- optional Username
- your password
- Member number in Gotlandskanin
