### ISSUE TITLE
let owners edit their rabbits

### ISSUE THREAD

**Issue by HenrikeW** [NBISweden/theherdbook#295]
Change permissions in the frontend to enable owners to actually edit their rabbits. 
Right now, only genebank managers and admins can edit rabbits. 
It's a frontend-only fix.

**Comment by jhagberg** [comment]
You should be able to edit all rabbits that are born in your herd. So edit if rabbits first number match the herd you manage. 

If you have bought rabbits from another herd you can not edit this you need to talk to the founder herd owner or the genebank manger for the breed.

**Comment by HenrikeW** [comment]
According to Slack from Sep 6th
```
"Jonas Hagberg  11:01 Uhr
A herd owner should be able to edit all animals they currently own
11:03 Uhr
that includes animals they bought from other herds "
```
That is how the component works right now, so I don't think there is anything to fix here.
This issue probably should have been closed long ago.

**Comment by jhagberg** [comment]
yes Think we can close this now
