### ISSUE TITLE
Things to fix with Digital Certificates

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#299]
On the PDF Generated

- [x]  NR field should be the generated Certificate number not the individual number
- [x] Ras should be written as "Gotlandskanin or Mellerudskanin"
- [x] Genbanksnummer should be the first part of number like "G1115! and  År, Kull, Individ should be the part after "-" so 1528
- [x] The above should be the same for all parents
- [x] Födelsedatum should be on the format YYYY-MM-DD
- [x] Intygas av should be the full name of the user "Namn Namnsson"
- [x] Medlmsnummer should be the member number for the Users. (Same as the herd number but without the G/M in front"
- [x] If I download the PDF no information on the parents are there.
- [x] There should be possible to download the certificate again from the system

**Comment by jonandernovella** [comment]
@jhagberg Except for the full name of the user, currently we have all the other fixes.
