### ISSUE TITLE
Current data issues: missing certificates

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/theherdbook#31]
There are 353 individuals with missing certificates.

Automatically adding certificates for these based on offspring relationships will result in certificates with `mf`, `ff` etc. suffixes where individuals across several generations are missing certificates.  I'm hoping this is ok.  This adds 144 certificates to the data but leaves 209 individuals with no certificate.

This is also related to commit 1caa180c1e880317b3226c8be1f26444834fab24.

**Comment by jhagberg** [comment]
What is a certificate here?

**Comment by jhagberg** [comment]
If its intyg its not related to anything we can infer from the data

**Comment by andkaha** [comment]
Certificates can be inferred by using the certificates from an offspring and adding `m` or `f` to the end of it.

Included in data issue summary document.
