### ISSUE TITLE
Fix certificate download for Google users

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/theherdbook#316]
Currently the certificate issuing webpage does not allow you to confirm your identity using Google credentials, but only local ones.

DoD: Create a link/button that redirects you to log in with Google.

**Comment by pontus** [comment]
One alternative to this is also setting up a local password and authenticating with that.

I haven't checked, but suppose Google support reauthentication, but not all possible/desirable authentication sources will support that (and this might well be saved in the browser, so I'm not sure I see the value of an additional authentication here).

I'm also unsure about what the actual requirement is, can @jhagberg clarify.

**Comment by jhagberg** [comment]
fixed by #435
