### ISSUE TITLE
Current data issues: invalid weights

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/theherdbook#33]
The following invalid weight measures exists:

* `3,5 n` for `572-1432`
* `2,5 n` for `997-1552`
* `slakt` for `718-1411`
* `n` for `694-1578`, `1202-1611` and `1202-1621`.

Also, since individuals `1185-1921` and `1185-1951` lack birth dates, their weight from "vikt u" (`3` and `3.3` respectively) can't be added.

I'm ignoring these.

**Comment by andkaha** [comment]
Included in data issue summary document.

**Comment by andkaha** [comment]
This seems to have been resolved.
