### ISSUE TITLE
Add validation for parent selection

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/theherdbook#348]
Make sure that admin and genebank owners can select correct data at registration, test mating and breeding events.

- [x] No founders should be able to be registered
- [x] Genebank owners can select father and mother that are alive but not in the active population from a user given date.
- [x] Herd owners should only be able to select mothers that belong to their herd and (active) fathers from any herd.

**Comment by jhagberg** [comment]
Not allowed to create new founders. 

Test mating should be able to select all active animals for the last 10 years

register animals should have the same rules for both male and females for Genebank manager
For herds owners, only the females belonging to my own herd should be selectable but for males the same rule with 10 years active.

The same rules for log mating should apply for herd owners. Only be able to select females from my own herd but males active for the last 10 year.
