### ISSUE TITLE
Breeding form UX improvements

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/theherdbook#355]
**EPIC**

- [x] Give better feedback about distance between breeding and birth
- [x] Make it simpler to add more records since currently it fails after adding a first record
- [x] Make sure we only allow to add breeding events with at least one individual from the owned herd
- [ ] #453

**Comment by pontus** [comment]
Ask clarification from org. Should we allow females from other herds?

**Comment by pontus** [comment]
Should breeding event show in the herd of the male? Probably not.

**Comment by jhagberg** [comment]
Email sent to Org

**Comment by jhagberg** [comment]
it should be allowed to borrow a Male from another herd. It should only generate one breeding event on the herd owning the female.  

Sometimes herds borrow females. This should be handled by the herd lending the female is selling the individual to the herd that wants to use her in breeding so the herd is now actually owning the female individul'
