### ISSUE TITLE
Establish consensus with active attribute

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/theherdbook#362]
We should decide between active or is_active and change the backend/frontend. This should fix the frontend filter for inactive individuals.

**Comment by HenrikeW** [comment]
Update: The assumption earlier was that backend is using `is_active` and frontend `active`. In that case, it had been  easy to change the frontend to match the backend. I checked it and it's not used in many cases. 
But there seems to be at least one situation where even the backend uses `active`: within the function `get_individuals` defined in `data_access.py`. This needs some further investigation.
