### ISSUE TITLE
Add a cookie banner

### ISSUE THREAD

**Issue by pontus** [NBISweden/theherdbook#374]
For legal reasons, it can be required to declare if a system uses e.g. cookies  or other data stored on a client machine (see e.g. eprivacy directive, https://edps.europa.eu/data-protection/our-work/publications/legislation/directive-2009136ec_en).

Also, from what I remember, logins won't work at all without cookies, so i'td be nice to explain that it's a requirement to use any non-public functionality.

**Comment by jhagberg** [comment]
closed by #566
