### ISSUE TITLE
Edit Individual Hull data is listed as undefined

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#385]
There is hull date information but they are all undefined 
Maybe we read in the wrong data or we can't display the data correctly?

Here is how it should be interpret 

Hull
Ägarens subjektiva bedömning. n = normalhull, f = fet (överviktig), m= mager (underviktig).

(Now we have Låg Normal Hög. We could chage it to Normal, fet, mager. ) Will check this with the mangers

**Comment by andkaha** [comment]
Do we want to store the Swedish words `mager`, `normal`, and `fet`?  Or do we want the English `skinny`, `normal`, and `fat`?  Or are there better words?

**Comment by jhagberg** [comment]
The python code says:
```
`bodyfat` should be a list formatted like:
    [{bodyfat: 'low' | 'normal' | 'high', date: 'yyyy-mm-dd'}, [...]]
```

so n = normal f=high m=low

**Comment by andkaha** [comment]
PR #397 is now ready for review.
