### ISSUE TITLE
Bug in Sell individual

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#411]
I can choose a selling date before the individual is born.
And thus I will still own the rabbit. 

Also, I could choose a date before the latest herd tracking entry. Like if a rabbit is born 2020-01-01 and reported 2020-12-31 the latest herd tracking data is 2020-12-31 but if I sell it and put the selling date 2020-12-01 then I still will be the owner of the rabbit. 

FIx so you cant choose a date before the rabbit is born. or you cant choose a date before the latest herd tracking entry for the rabbit.

**Comment by jhagberg** [comment]
Its the same bug in the register form if the manager try to sell the rabbit before its born it will fail if we merge #413 so we need to disable dates before birt date in register from also

**Comment by HenrikeW** [comment]
There is an easy way of setting a min date to the date picker in the frontend. As far as I can see, the min date should always be one day after the latest herd tracking date, right? 
At least, I use that for the yearly report and reporting an animal as dead. 
I could make the min date global, then we could reuse it here.

**Comment by jhagberg** [comment]
yes in Register animal we do not have any herd tracking information if we want to register the sell the same time as we create the individual so then can we  use mindate + one date = user input in form "födelsedatum" ?

**Comment by HenrikeW** [comment]
Was fixed by #418 ?

**Comment by jhagberg** [comment]
yes
