### ISSUE TITLE
Info text on herd page information

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#412]
Information text for herd users.

**Det ska finnas en inforuta på sidan med följande text:**
Du som är genbanksinnehavare fyller själv i de kontaktuppgifter du vill att andra
genbanker ska se för att underlätta kommunikation mellan genbankerna. Du kan själv,
när som helst, gå in och ändra i dina kontaktuppgifter. OBS! En ändring här slår inte
igenom till föreningens medlemsmatrikel, så om du exempelvis flyttat eller bytt e-post,
måste du också meddela det till föreningens kassör, för ändring i medlemsmatrikeln.
Medlemsmatrikeln används bara för föreningens interna administration, och är inte
offentlig.

**Comment by LillSara** [comment]
Byt ut genbank till besättning?
