### ISSUE TITLE
Error when updating individuals with digital certificates

### ISSUE THREAD

**Issue by HenrikeW** [NBISweden/theherdbook#431]
I'm trying to use the edit form to update an individual that has a digital certificate.
A `PATCH` request is sent to `/api/individual`. It contains an individual object.
The response is a `500` with the payload `{
  "message": "argument of type 'int' is not iterable", 
  "status": "error"
}
`
This doesn't happen when editing individuals that don't have digital certificates. 

Right now, the frontend includes all possible fields in the individual object that is sent in the request, even those that haven't changed. Could that cause the issue?

**Comment by jhagberg** [comment]
What does the backend says?

**Comment by jhagberg** [comment]
I get this when trying to issue a digital Certifcate to a newly added rabbit

I still see the usernme password I think we removed that since the Google auth users does not have  a password.

I was thinking we could replace this by 

Bekräfta detta certifikat genom att skriva in ditt besättnings nummer

**Comment by jhagberg** [comment]
This commit changed the behaviour and is now failing when creating digital certificate

https://github.com/NBISweden/theherdbook/commit/44baa3a59e635e5c0bd101e3a6ddfd6d0af8284b

https://github.com/NBISweden/theherdbook/pull/402

**Comment by airenzp** [comment]
None of this erros is happening anymore. When creating certificates one needs to use the built images, not precompiled images. Otherwise it fails

**Comment by jhagberg** [comment]
This is still an issue for me


File "./utils/data_access.py", line 1004, in update_individual
herdbook-main              |     individual = form_to_individual(form, user)
herdbook-main              |   File "./utils/data_access.py", line 793, in form_to_individual
herdbook-main              |     if fields and "number" in fields:  # parents
herdbook-main              | TypeError: argument of type 'int' is not iterable

**Comment by airenzp** [comment]
I found the reason. It happens to users that are not managers. The code failing is happening when the user is not manager, see, it was this line: 

`    if individual.id and not can_manage:
        for admin_field in [field for field in admin_fields if field in form]:
            fields = form.get(admin_field, None)
            **if fields and "number" in fields:  # parents**
                changed = (
                    form[admin_field]["number"]
                    != getattr(individual, admin_field).number`

It must be because there is only one field edited

**Comment by jhagberg** [comment]
This is no longer an issue
