### ISSUE TITLE
Show "Hona" "Hane" in frontend

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#455]
In 
individual_view
herd_view 
and 
genebank_view 

Show swedish Hane and Hone instead of male and female.

**Comment by HenrikeW** [comment]
In individual.view the sex is shown like this:

```
<dt>Kön:</dt>
<dd>{individual?.sex}</dd>
<dt>
```
Instead it should be possible to write something like this:
```
<dt>Kön:</dt>
<dd>{individual?.sex == "male" ? "Hane" : individual.?sex == "female" ? "Hona"}</dd>
<dt>
```
Don't have time to test it right now, but it's worth a try.

**Comment by HenrikeW** [comment]
In herd_view and genebank_view I think the information on sex actually is rendered in the filter_table component. In that one I'd need to look a bit closer how to change it.
