### ISSUE TITLE
Redigera individ så ändras hela kullen.

### ISSUE THREAD

**Issue by LillSara** [NBISweden/theherdbook#531]
**Beskriv felet**
Om jag vill redigera mor eller far till EN kanin, så ändras mor och far för hela kullen.

**Hur man reproducerar**
Steg för att reproducera beteendet/felet:
1. Gå till "min besättning"
2. Klicka på "lista över individer"
5. Välj individ.
6. Tryck på redigera individ.
7. Tryck på redigera parningstillfälle.
8. Om man redigerar så ändrar man alla kaninen från det parningstillfället.

**Förväntat beteende**
Om jag "redigerar individ" så vill jag att bara den individens data ändras.

**Comment by jhagberg** [comment]
Detta är nu fixat och är live på testserver. Det går att ändra på föräldrar men det verkar inte gå att uppdatera själva händelsen om man inte ändrar föräldrar. Jag får kolla på det efter midsommar
