### ISSUE TITLE
Inga mödrar att välja på...

### ISSUE THREAD

**Issue by wassen1** [NBISweden/theherdbook#533]
**Inga mödrar att välja på**
När man skall lägga till en ny individ i sin genbank så går det inte att välja mor till den.

**Hur man reproducerar**
Steg för att reproducera beteendet/felet:
1. Logga in till avelsprogrammet.
2. Välj min besättning i hamburgermenyn.
3. Klicka på lägg till.
4. Klicka på välj mor.

**Förväntat beteende**
Det borde komma upp träffar på modern på samma sätt som det gör i fältet välj far. Endast min egen hona dyker upp som träff.

**Skärmbilder**
<img width="838" alt="image" src="https://user-images.githubusercontent.com/16906602/174732363-dbadb1b4-44ac-47c1-93a2-cf0c1d3020a4.png">

**Dator:**
- OS: Windows
- Webbläsare: Chrome
- Version: 102.0.5005.115 (Officiell version) (64 bitar)

**Ytterligare information**
Jag har dubbelkollat med gamla avelsprogrammet att honan finns inlagd så den borde dykt upp.

**Comment by jhagberg** [comment]
Hej

Som besättnings ägare får du bara registrera dina egna kaniner. Om honan du vill registrera en avkomma ifrån är i din ägo ska du kunna få upp henne som val. Har du lånat honan för avel så måste den ägande besättningen "sälja" honan till dig och när du sedan lämnar tillbaka den får du "sälja" tillbaka den till rätt besättning. Du ansvarar för din egen besättning och kan inte registrera djur som är födda i en annan besättning. Saknar du en kanin du äger kan du be den andra besättningen att registrera djuret och sedan sälja det till dig eller helt enkelt be Genbanksansvarig om hjälp om du har ett Intyg. 

Hoppas det förklarar, föreslå gärna någon text om detta i manualen!.

**Comment by jhagberg** [comment]
Kaninen finns där men ägs inte av dig då får du inte heller registrera avkommor från det djuret, du måste ha kontroll och djuret i din ägo. Precis som om du skulle utfärda ett vanligt intyg på papper. Det får du endast göra med djur i din egen besättning. 
https://test.gotlandskaninen.se/individual/G922-1821

**Comment by wassen1** [comment]
Jag hade visst provat med fel individnummer. Men principen klargjordes ändå :) Det är G922-2114 som inte blivit registrerad ännu och därför inte går att få fram här tyvärr.
