### ISSUE TITLE
Adressfältet ändras.

### ISSUE THREAD

**Issue by wassen1** [NBISweden/theherdbook#534]
**Adressfältet ändras**
Fel uppgifter visas i adressfältet. Ett onödigt kommatecken visas också.

**Hur man reproducerar**
Steg för att reproducera beteendet/felet:
1. Gå till "min besättning"
2. Klicka på "edit".
3. Fyll i postnummer och Postort.
4. Lämna "Gatuadress" tom.
5. Klicka på "stop editing".
6. Klicka på "Besättning" för en av dina kaniner. 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/16906602/175040494-a63e9707-5a39-40ed-ac93-7f2662e1f1b7.png">

7. Då visas fel adress uppe vid kontaktperson.
8. Om du då klickar på Edit så har uppgifter vandrat från postnummer och postort till gatuadress och värdet null visas.

**Förväntat beteende**
Samma uppgifter som lagts in i adressfälten borde förbli samma även om du gör ovanstående moment.

**Skärmbilder**
<img width="326" alt="image" src="https://user-images.githubusercontent.com/16906602/175038964-31e489e3-a8b2-43c3-a962-e4d86ad150d7.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/16906602/175039882-a4f90fe9-db39-4f93-8f02-6bde1b438568.png">

**Dator:**
- OS: Windows
- Webbläsare: Chrome
- Version: Version 102.0.5005.115 (Officiell version) (64 bitar)

**Comment by jhagberg** [comment]
Denna ändring är nu Live på test servern.
