### ISSUE TITLE
User-accessible data health checks

### ISSUE THREAD

**Issue by andkaha** [NBISweden/theherdbook#76]
A user would need to be able to check certain things in the web interface, so that questionable data can be corrected. This is primarily useful for checking the data loaded from the manually curated Excel spreadsheets.

This includes

* Individuals with no gender (or other incomplete data, such as no colour)
* Duplicated certificates
* Formatting of certificates and "numbers"

**Comment by jhagberg** [comment]
We have health checks when importing data
