### ISSUE TITLE
URL to individual to use Nummer instead of Database ID

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#88]
For example, this URL is using a internal database ID that is unknown to Humans.

https://herd.gotlandskaninen.se/individual/9537

Should be https://herd.gotlandskaninen.se/individual/ or even better just

https://herd.gotlandskaninen.se/G1158-1624

**Comment by norling** [comment]
Very true! Should I add routes for `G<id>` -> herd, and `G<id>-<id>` -> individual?
