### ISSUE TITLE
Wrong number in Individ listan

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#89]
Moder och fader i individ listan bör lista Nummret för fadern alltså det som börjar med G

**Comment by norling** [comment]
Could you add a link to where this should be fixed?

**Comment by jhagberg** [comment]
https://herd.gotlandskaninen.se/genebanks/1/individuals

**Comment by jhagberg** [comment]
But maybe its okey to just list the Name also

**Comment by norling** [comment]
closed by 1b7120ea99
