### ISSUE TITLE
Current data issues: dates

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/theherdbook#9]
The following individuals have a birth date of `12019-03-12`.  Assuming this should be `3/12/2019`:

```
1330-1921
1330-1922
1330-1923
1330-1924
```

I'm changing these manually in the CSV file.

**Comment by andkaha** [comment]
Additionally, the following individuals lack any type of birth dates:

* <strike>`G1185-1921`</strike> (updated dataset fixes this one)
* <strike>`G1185-1951`</strike> (updated dataset fixes this one)

**Comment by kusalananda** [comment]
Additionally, individual `694-1931` has a birth date of `2019-`.  I will interpret this as `1/1/2019`.

**Comment by andkaha** [comment]
All fixed.
