### ISSUE TITLE
Funderingar 1

### ISSUE THREAD

**Issue by Lekander47** [NBISweden/theherdbook#92]
2020-07-28
Besättningar
Det bör finnas en snabbsökfunktion. Om jag exempelvis är intresserad av genbank G1385 måste jag hålla på att klicka mig neråt i listan i nästan all oändlighet.

Administrera besättningar
När jag ska administrera exempelvis genbank 5, så kommer genbank 44 upp, men med genbank 5:s kaniner. Skriver jag in namnet på innehavaren så byts det konstiga numret ut mot namnet – bra. Men förvirrande med det först uppdykande namnet. 
Sparfunktionen fungerar inte. När jag skrivit in något och trycker på sparaknappen, sparas inget.

**Comment by jhagberg** [comment]
Hej tackar för din feedback. Angående numren så är det de interna unika databas id numren som visas. Det ligger på agenda att fixa så det visar de numren som vi är intresserade av.  

Relaterat till #89
