### ISSUE TITLE
Funderingar 2

### ISSUE THREAD

**Issue by Lekander47** [NBISweden/theherdbook#93]
2020-07-29
Administrera besättningar
Det bör finnas en funktion där genbanksansvariga noterar ett val: Aktiva genbanker / Avslutade genbanker. För avslutade genbanker ska kontaktuppgifterna i samband med avslutet raderas (av genbanksansvarig). Bra kanske också med en funktion där man kan välja ”Visa bara aktiva genbanker”
De flesta genbankerna för gotlandskanin är faktiskt avslutade. I dagsläget är 477 avslutade och 246 aktiva

**Comment by jhagberg** [comment]
Bra funktioner!
